export const GET_DATA_PRODUCT = "GET_DATA_PRODUCT";
export const GET_DATA_PRODUCT_BY_ID = "GET_DATA_PRODUCT_BY_ID";
export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const PAGINATION = "PAGINATION";